apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.superuserSecret.name }}
  namespace: {{ .Values.cnpg.namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.superuserSecret.username }}
  password: {{ .Values.superuserSecret.password }}
