apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cnpg.name }}
  namespace: {{ .Values.cnpg.namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.cnpg.namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
spec:
  instances: {{ .Values.cnpg.instances }}
  projectedVolumeTemplate:
    sources:
      - configMap:
          name: {{ .Values.cnpg.schemaConfigMap.name }}
          items:
            - key: schema.sql                                           # Matches ConfigMap data key
              path: schema/enginevector-lottery-schema.sql              # Mount location in /projected/
  primaryUpdateMethod: {{ .Values.cnpg.primaryUpdateMethod }}
  primaryUpdateStrategy: {{ .Values.cnpg.primaryUpdateStrategy }}
  enableSuperuserAccess: {{ .Values.cnpg.enableSuperuserAccess }}
  monitoring:
    enablePodMonitor: {{ .Values.cnpg.monitoring.enablePodMonitor }}
  bootstrap:
    initdb:
      database: {{ .Values.cnpg.bootstrap.initdb.database }}
      owner: {{ .Values.cnpg.bootstrap.initdb.owner }}
      dataChecksums: true
      encoding: {{ .Values.cnpg.bootstrap.initdb.localeSettings.encoding }}
      localeCType: {{ .Values.cnpg.bootstrap.initdb.localeSettings.localeCType }}
      localeCollate: {{ .Values.cnpg.bootstrap.initdb.localeSettings.localeCollate }}
      secret:
        name: {{ .Values.appUserSecret.name }}
      postInitApplicationSQLRefs:
        configMapRefs:
         - name: {{ .Values.cnpg.schemaConfigMap.name }}
           key: {{ .Values.cnpg.schemaConfigMap.key }}
  superuserSecret:
        name: {{ .Values.superuserSecret.name }}
  postgresql:
    parameters:
      logging_collector: "{{ .Values.cnpg.postgresql.parameters.logging_collector }}"
      log_statement: "{{ .Values.cnpg.postgresql.parameters.log_statement }}"
      log_directory: "{{ .Values.cnpg.postgresql.parameters.log_directory }}"
      log_filename: "{{ .Values.cnpg.postgresql.parameters.log_filename }}"
      log_min_messages: "{{ .Values.cnpg.postgresql.parameters.log_min_messages }}"
      log_rotation_size: "{{ .Values.cnpg.postgresql.parameters.log_rotation_size }}"
      log_rotation_age: "{{ .Values.cnpg.postgresql.parameters.log_rotation_age }}"
      log_truncate_on_rotation: "{{ .Values.cnpg.postgresql.parameters.log_truncate_on_rotation }}"
      max_connections: "500"
      max_slot_wal_keep_size: "64MB"
      wal_keep_size: "64MB"
      wal_level: {{ .Values.cnpg.postgresql.parameters.walLevel }}
    pg_hba:
    {{- range .Values.cnpg.postgresql.pg_hba }}
      - {{ . }}
    {{- end }}
    synchronous:
      method: {{ .Values.cnpg.postgresql.synchronous.method }}
      number: {{ .Values.cnpg.postgresql.synchronous.number }}
  storage:
    size: {{ .Values.cnpg.storage.size }}
  resources:
    requests:
      cpu: {{ .Values.cnpg.cpuRequest }}
      memory: {{ .Values.cnpg.memoryRequest }}
    limits:
      cpu: {{ .Values.cnpg.cpuLimit }}
      memory: {{ .Values.cnpg.memoryLimit }}